### ISSUE TITLE
Consider depending on mime.rs

### ISSUE THREAD

**Issue by nox** [flier/rust-mime-sniffer#1]
Is there any particular reason you return strings instead of `Mime` values?

**Comment by flier** [comment]
I have consider it before, but seems `mime.rs` hard to desribe MIME type in a compact notation
```rust
assert_eq!(Mime(TopLevel::Application,
                SubLevel::Ext(String::from("vnd.ms-powerpoint")),
                []),
           req.sniff_mime_type_ext().unwrap());
```
anyway, added a `MimeTypeSnifferExt` trait to return `Mime` type.

**Comment by nox** [comment]
http://hyper.rs/mime.rs/mime/macro.mime!.html

```rust
mime!(Application/("vnd.ms-powerpoint"))
```

**Comment by flier** [comment]
great, it seems good enough
